### PR TITLE
Update build.jl with new URL for windows binaries

### PR DESCRIPTION
**Pull request by toivoh**
Old URL was outdated.

### CODE REVIEW

**Comment by acroy** [comment]
Thanks! This seems to work, but let's wait until everything is finished ...

**Comment by toivoh** [comment]
AppVeyor Julia 0.4 passed, nightly 64 bit segfaults somehow, while nightly 32 bit says

    ERROR: LoadError: LoadError: cfunction: no method exactly matched the required type signature
    (function not yet c-callable) in #cvode#

as does Travis nightly. Travis Julia 0.4 also passed (push, pr doesn't seem to be done yet).

**Comment by toivoh** [comment]
Seems to be the same story with the last Travis tests.

**Comment by acroy** [comment]
Yeah, as long as 0.4 works I would say it is Ok. Let's merge this ...

**Pull request merged**
