### PR TITLE
Change nvlength to use Clong instead of Int

### PR DESCRIPTION
**Pull request by tshort**

### CODE REVIEW

**Comment by tshort** [comment]
Now, I'm more confused. I thought @acroy found the answer in #41, but this is failing on AppVeyor on win32, but passed in #41 where Int32 was used.

**Comment by acroy** [comment]
It seems that the test never ran. The message is "Build execution time has reached the maximum allowed time for your plan (40 minutes)." Maybe you can try to restart the build & test?

**Comment by tshort** [comment]
Restarting fixed it...

**Comment by tshort** [comment]
I'm not sure on the protocol for merging changes into Sundials these days. Is it okay to merge this?

**Comment by ViralBShah** [comment]
Yes, go for it!

**Pull request merged**
