### PR TITLE
Make Sundials.jl work with Julia 0.4

### PR DESCRIPTION
**Pull request by christianhaargaard**
A quick fix for 0.4. As discussed in Issue #54 the c-bindings should probably be redone using Clang.jl.

### CODE REVIEW

**Comment by acroy** [comment]
Thanks! The CI is failing since we explicitly test with julia 0.3. This should be removed from `.travis.yml` and the `REQUIRE` should be updated as well. Could you also squash your commits into a single one?

**Comment by christianhaargaard** [comment]
It required some googling, and a couple of tries, but I think I managed to squash the commits together. I also updated `REQUIRE` to ask for julia 0.4. The `.travis.yml` file only mentions `nightly` and `release` though.

**Comment by acroy** [comment]
Yeah, I am sometimes also struggling with this. It seems that your fork was not in sync with this repo though. You have to rebase your branch against the current master (e.g. update your master branch and then rebase 04upgrade). If you look into [the current .travis.yml](https://github.com/JuliaLang/Sundials.jl/blob/master/.travis.yml) you will see `0.3` and `0.4`. This was changed about 12 days ago.

**Comment by christianhaargaard** [comment]
It looks like I'm severely messing this up.. I think I will try to checkout my own branch again, and start the merge over.

**Comment by christianhaargaard** [comment]
I'll close this pull request and make another. Sorry for all the confussion. Git and I are just getting to know each other.

**Pull request closed without merging**
