### PR TITLE
Remove duplicated method definitions, which produced warnings

### PR DESCRIPTION
**Pull request by jgoldfar**
see https://github.com/JuliaLang/julia/commit/8dfc5403015684bd4878834d2c42e808fd7cbd2a

Don't think I removed anything that wasn't duplicated, but worth a look to make sure.

### CODE REVIEW

**Comment by jgoldfar** [comment]
BTW, the package now fails to run (at least the simplified interface does) using the latest Julia build. Perhaps to do with the changes to cfunctions?

**Comment by acroy** [comment]
Thanks! I haven't checked all instances, but it looks reasonable.

Regarding the failure: the question is if we can support both 0.4 and 0.5 in an easy way right now. If not, IMO we shouldn't worry about 0.5 compatibility (unless someone wants/needs it badly).

**Comment by jgoldfar** [comment]
I've been following development on 0.5 with interest, so I'd be happy to work on supporting both. I would need a bit more to go on than https://github.com/JuliaLang/julia/pull/13412#issuecomment-175200009 and https://github.com/JuliaLang/julia/pull/13412#issuecomment-175224594... I've been experimenting around those ideas but evidently don't have anything yet.

**Comment by acroy** [comment]
Sorry, I missed the last sentence. I guess we can merge this one as well ...

**Comment by tkelman** [comment]
Would the generator script need updating to avoid adding these back? Or is that something that is unlikely to need to be run again?

**Comment by jgoldfar** [comment]
Yes to both AFAIK; the workings of libclang and Clang.jl are a bit of a black box to me, but the low-level wrappers don't need regeneration often (or ever, depending on how core Julia changes 😄)

**Pull request merged**
